In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import preprocessing, svm
from sklearn.preprocessing import LabelEncoder 
from sklearn.model_selection import train_test_split
from sklearn import metrics

/Users/kislayadityaoj/opt/anaconda3/lib/python3.9/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.26.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [2]:
dataset = pd.read_csv('../../Datasets/salaries.csv')

In [3]:
dataset

work_year experience_level employment_type                 job_title  \
0           2024               MI              FT            Data Scientist   
1           2024               MI              FT            Data Scientist   
2           2024               MI              CT            Data Scientist   
3           2024               MI              CT            Data Scientist   
4           2024               MI              FT      Data Science Manager   
...          ...              ...             ...                       ...   
16489       2020               SE              FT            Data Scientist   
16490       2021               MI              FT  Principal Data Scientist   
16491       2020               EN              FT            Data Scientist   
16492       2020               EN              CT     Business Data Analyst   
16493       2021               SE              FT      Data Science Manager   

        salary salary_currency  salary_in_usd employee_residence  \
0       120000             USD         120000                 AU   
1        70000             USD          70000                 AU   
2       130000             USD         130000                 US   
3       110000             USD         110000                 US   
4       240000             USD         240000                 US   
...        ...             ...            ...                ...   
16489   412000             USD         412000                 US   
16490   151000             USD         151000                 US   
16491   105000             USD         105000                 US   
16492   100000             USD         100000                 US   
16493  7000000             INR          94665                 IN   

       remote_ratio company_location company_size  
0                 0               AU            S  
1                 0               AU            S  
2                 0               US            M  
3                 0               US            M  
4                 0               US            M  
...             ...              ...          ...  
16489           100               US            L  
16490           100               US            L  
16491           100               US            S  
16492           100               US            L  
16493            50               IN            L  

[16494 rows x 11 columns]

## To-do

to predict -> salary 

Data cleaning : 
1. To drop -> salary , salary_currency , work_year, remote_ratio
2. Assign [ experience_level , company_size , employment_type] according to priorities

Normalization

Training:
1. X -> everything excluding salary column 
2. Y -> salary

In [4]:
dataset = dataset.drop(['salary', 'salary_currency' , 'work_year' , 'remote_ratio'], axis=1)
dataset.head()

experience_level employment_type             job_title  salary_in_usd  \
0               MI              FT        Data Scientist         120000   
1               MI              FT        Data Scientist          70000   
2               MI              CT        Data Scientist         130000   
3               MI              CT        Data Scientist         110000   
4               MI              FT  Data Science Manager         240000   

  employee_residence company_location company_size  
0                 AU               AU            S  
1                 AU               AU            S  
2                 US               US            M  
3                 US               US            M  
4                 US               US            M

In [21]:
# This label encoder label encodes randomly 

# le = LabelEncoder()
# #dataset["company_size"] = le.fit_transform(dataset["company_size"])
# dataset["job_title"] = le.fit_transform(dataset["job_title"])
# dataset["employee_residence"] = le.fit_transform(dataset["employee_residence"])
# dataset["company_location"] = le.fit_transform(dataset["company_location"])

In [22]:
# dataset.head()

In [7]:
# This split the columns -> one hot encoding 

#Y = pd.get_dummies(data = dataset , columns = ['employment_type']

In [8]:
cols = dataset.columns
arr = np.asarray(dataset[cols])
arr = arr.transpose()
arr

array([['MI', 'MI', 'MI', ..., 'EN', 'EN', 'SE'],
       ['FT', 'FT', 'CT', ..., 'FT', 'CT', 'FT'],
       ['Data Scientist', 'Data Scientist', 'Data Scientist', ...,
        'Data Scientist', 'Business Data Analyst',
        'Data Science Manager'],
       ...,
       ['AU', 'AU', 'US', ..., 'US', 'US', 'IN'],
       ['AU', 'AU', 'US', ..., 'US', 'US', 'IN'],
       ['S', 'S', 'M', ..., 'S', 'L', 'L']], dtype=object)

In [9]:
# This function take the string based column and assign prioritized value accoring to avg salaries 
# More the avg salary better the number 

def prioritize_encoding(column , salary):
    s = column.size 
    d = {}
    for i,j in zip(column , salary):
        if i in d:
            d[i][0]+=j
            d[i][1]+=1
        else :
            d[i]= [ j , 1 ]
    val = []
    for key in d :
        val.append((d[key][0]/d[key][1] , key ))
    val = sorted(val, key=lambda x:x[0])
    final = dict()
    count = 0
    for i,j in val:
        final[j]= count 
        count += 1
    
    for i in range(len(column)) :
        column[i]=final[column[i]]
    #return column
    

In [10]:
# Encodes the required columns 

prioritize_encoding(arr[0] , arr[3])
prioritize_encoding(arr[1] , arr[3])
prioritize_encoding(arr[2] , arr[3])
prioritize_encoding(arr[4] , arr[3])
prioritize_encoding(arr[5] , arr[3])
prioritize_encoding(arr[6] , arr[3])

In [11]:
arr = np.asarray(arr)
arr

array([[1, 1, 1, ..., 0, 0, 2],
       [3, 3, 2, ..., 3, 2, 3],
       [111, 111, 111, ..., 111, 22, 140],
       ...,
       [76, 76, 83, ..., 83, 83, 18],
       [67, 67, 73, ..., 73, 73, 12],
       [0, 0, 2, ..., 0, 1, 1]], dtype=object)

In [12]:
# just checking it by converting back to dataframe 

copy_arr = arr
copy_arr = copy_arr.transpose()
df = pd.DataFrame(copy_arr , columns = cols)
df.head()

experience_level employment_type job_title salary_in_usd employee_residence  \
0                1               3       111        120000                 76   
1                1               3       111         70000                 76   
2                1               2       111        130000                 83   
3                1               2       111        110000                 83   
4                1               3       140        240000                 83   

  company_location company_size  
0               67            0  
1               67            0  
2               73            2  
3               73            2  
4               73            2

## Start training 

In [13]:
arr

array([[1, 1, 1, ..., 0, 0, 2],
       [3, 3, 2, ..., 3, 2, 3],
       [111, 111, 111, ..., 111, 22, 140],
       ...,
       [76, 76, 83, ..., 83, 83, 18],
       [67, 67, 73, ..., 73, 73, 12],
       [0, 0, 2, ..., 0, 1, 1]], dtype=object)

In [14]:
Y = arr[3]
#Y = Y / Y.max(axis=0)
Y.shape 

(16494,)

In [15]:
X = np.delete(arr , 3 , axis=0 )
X = X.transpose()
X = X / X.max(axis=0)
X.shape 

(16494, 6)

In [16]:
X_train , X_test , Y_train , Y_test = train_test_split(X, Y, test_size = 0.2)

In [17]:
model = LinearRegression()
model.fit(X_train, Y_train)

LinearRegression()

In [18]:
print(model.coef_)
model.intercept_

[ 67301.29182771   7467.35648082 133131.75480317  82020.48990482
  66296.32542081    347.33602152]


-120725.8362105997

In [19]:
Y_pred = model.predict(X_test).flatten()    # predicted value of y_test
#Y_test = Y_test.to_numpy().flatten()

print(Y_pred.shape)
print(Y_test.shape)
print(Y_test)
print(Y_pred)

(3299,)
(3299,)
[185000 83300 70000 ... 144000 90000 76300]
[165521.32519788  82616.15308326  80844.14342525 ... 175895.22816955
 147410.02082684 103320.93319722]


In [20]:
score = model.score(X_test, Y_test)
print(score)

0.30713646383985127


## Scores

No normalization accuracy -> 0.3030163423516792 <br>
Only X normalized -> 0.33412542662336675 <br>
Both Normalized -> 0.31639566033343036